### PR TITLE
Ask Participant to Rate Confidence After Each First Submission

### PR DESCRIPTION
**Pull request by MichaelPascale**
The `Probe` class makes it possible to create a modal dialogue with an arbitrary number of items. Implemented likert and VAS type items for the purposes of this post-trial confidence.

image

Usage is like so:
```js
const p = new Probe('intertrial');

p.add_analog_field(
        'confidence-analog', 
        'Please rate how <u>confident</u> you feel about your solution.',
        ['Not at all confident', 'Fully confident']
    )
    .initialize(document.body, function (data) {
        console.log(data.get('confidence-analog'));
    });

p.open();
```

### CODE REVIEW

**Review by lbakst — APPROVED** [review]
The changes look great; appreciate all your work on this!

**Comment by MichaelPascale** [comment]
**Comments from lbakst:**

1. I agree that the sliding scale is likely preferable to the likert scale.
    - :white_check_mark:
2. It looks like the sliding scale can only move in increments of 10% -- maybe it's worth making this more flexible? Or did you feel like there were some analyses that would benefit from that kind of binned confidence ratings? 
    - _This is easy enough to change; I agree, now that you mention it._
3. I think moving the correct/incorrect feedback to the pop up would be useful. I think it would feel more natural to see it where you've been looking, rather than back at the original submit button. (This likely means also implementing a pop up for feedback after the second submit or a time out -- if there is a second submit or a time out -- to keep it consistent.)
    - _Neat! That makes sense; we can do a second pop-up._
4. I noticed that if I don't fill out the likert scale, it prompts me to select an answer. I like that because it means that I can't submit a confidence rating that is either blank or any kind of default answer. I'm not sure if there's a way to implement that for the sliding scale -- typically the slider is already present somewhere. Maybe there could be a similar kind of alert if the participant hasn't moved the slider at all? I'd love your thoughts on this.
    - _The HTML slider input doesn't do anything when you mark it as required since it has to start on a value. I could just add something to detect this I guess, and the participant would just have to move it away and back if, say, it started at 50%._
5. Somewhat relatedly, we might want to think about whether we always want the slider to start at 50% confident or if we want to vary it or... something else. I think 50% is a very reasonable starting point, but we should just think about it a bit.
    - _Varying it would be interesting... I could maybe create a custom component where there is no slider, and they just click directly on the scale..._
6. Finally, we should assess this at the eye tracker, but my instinct is that it would be nice for the pop up to be centered vertically on the screen instead of in the upper part. Let's just make a mental note to think about this when we're at the tracker on Monday.
    - :white_check_mark:

**Comment by MichaelPascale** [comment]
**Comments from Testing on 2024-01-08**

- Send to Python a signal that the confidence screen was reached.
- The position of the probe modal is at a good height, but it would be nice if it were centered over the input query grid.
- The order of logging for submit and ptProbeSubmit should be considered.
Screen Shot 2024-01-08 at 2 18 17 PM
- Screen resizing issues were most likely the result of not having the external monitor plugged in when PsychoPy was started.

**Comment by MichaelPascale** [comment]
**Comments from Testing on 2024-01-30**
- Submit event must happen _after_ feedback (at least, the eyetracker must stop recording after feedback)
- Confidence probe should be moved to the very center of the screen
- The should be displayed in brighter red
- A signal for the confidence probe can be sent to the eyetracker (send 'c' over psychopy pipe).
- Avoid sending rapid messages to psychopy
- Check font sizes
- Copy in demo to this repository and merge with latest changes.
- Feedback is skipped on breaks, change this behavior

**Comment by MichaelPascale** [comment]
- Encode version number in JSON.
- Provide ongoing printout of accuracy.

**Pull request merged**
